// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_traveler = "CgkIuNnUl9AYEAIQFA"; // <GPGSID>
        public const string achievement_jack_of_all_trades = "CgkIuNnUl9AYEAIQEA"; // <GPGSID>
        public const string achievement_an_unaffordable_amount = "CgkIuNnUl9AYEAIQBw"; // <GPGSID>
        public const string achievement_the_misogynist = "CgkIuNnUl9AYEAIQEg"; // <GPGSID>
        public const string achievement_the_slasher = "CgkIuNnUl9AYEAIQCw"; // <GPGSID>
        public const string achievement_the_avenging_boxer = "CgkIuNnUl9AYEAIQCg"; // <GPGSID>
        public const string achievement_inventor = "CgkIuNnUl9AYEAIQBg"; // <GPGSID>
        public const string achievement_toilet_paper = "CgkIuNnUl9AYEAIQAQ"; // <GPGSID>
        public const string achievement_lust = "CgkIuNnUl9AYEAIQDA"; // <GPGSID>
        public const string achievement_romantic_story = "CgkIuNnUl9AYEAIQAg"; // <GPGSID>
        public const string achievement_freedom = "CgkIuNnUl9AYEAIQEQ"; // <GPGSID>
        public const string achievement_wilkinscoffee = "CgkIuNnUl9AYEAIQAw"; // <GPGSID>
        public const string achievement_the_medic = "CgkIuNnUl9AYEAIQDQ"; // <GPGSID>
        public const string achievement_the_novice = "CgkIuNnUl9AYEAIQBQ"; // <GPGSID>
        public const string achievement_stalker = "CgkIuNnUl9AYEAIQBA"; // <GPGSID>
        public const string achievement_thief = "CgkIuNnUl9AYEAIQDg"; // <GPGSID>
        public const string achievement_the_gangster = "CgkIuNnUl9AYEAIQCQ"; // <GPGSID>
        public const string achievement_wet_pants = "CgkIuNnUl9AYEAIQFg"; // <GPGSID>
        public const string achievement_safecracker = "CgkIuNnUl9AYEAIQDw"; // <GPGSID>
        public const string achievement_alchemy = "CgkIuNnUl9AYEAIQFQ"; // <GPGSID>
        public const string achievement_blabbermouth = "CgkIuNnUl9AYEAIQCA"; // <GPGSID>
        public const string achievement_cool_car = "CgkIuNnUl9AYEAIQEw"; // <GPGSID>

}

